### PR TITLE
feat: additional request methods :head :options :patch :trace

### PR DESCRIPTION
**Pull request by fabrice8**
## Description
1. I noticed the router interface doesn't provide `HEAD`, `OPTIONS`, `PATCH`, `TRACE` request methods yet.
2. And I proposed changing `res.set` to `res.header` in the response class, to make it explicit that headers are those being set.
## Type of Change

- [x] ✨ New feature (non-breaking change which adds functionality)
- [ ] 🛠️ Bug fix (non-breaking change which fixes an issue)
- [x] ❌ Breaking change (fix or feature that would cause existing functionality to change)
- [x] 🧹 Code refactor
- [ ] ✅ Build configuration change
- [ ] 📝 Documentation
- [ ] 🗑️ Chore

### CODE REVIEW

**Review by codekeyz — COMMENTED** [review]
Nice work 🔥,

**Comment by codekeyz** [comment]
The CI is failing, https://github.com/codekeyz/pharaoh/actions/runs/6972318207/job/18974717589?pr=54

@fabrice8 Please look into it. I think you missed the implementation on the Pharaoh itself.

**Comment by fabrice8** [comment]
My bad. I might have missed update of the `set` method within `$Response interface`

**Review by codekeyz — APPROVED** [review]

**Comment by codekeyz** [comment]
Finally nailed it. Thanks man @fabrice8 🔥

**Pull request merged**
